name: OS Compatibility Check

on:
  workflow_dispatch: # Permite ejecuci√≥n manual

jobs:
  os-check:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build and Test
        shell: bash
        run: mvn clean verify -Ddependency-check.skip=true -Dfile.encoding=UTF-8 -Djava.awt.headless=true

      - name: Generate HTML Report
        if: always()
        shell: bash
        run: mvn surefire-report:report-only -Ddependency-check.skip=true

      - name: Upload Test Report
        if: always() # Se ejecuta incluso si fallan los tests
        uses: actions/upload-artifact@v4
        with:
          name: test-report-html-${{ matrix.os }}
          path: target/site/

